improvement(main.py): Exacting latest python driver tags
scylladb/python-driver-matrix pull request #27
Opened 2021-12-12 12:55 UTC by Orenef11

2021-12-14 21:44 UTC, roydahan requested changes
1. Small suggestion to fix typo + better message.
2. Please fix the typo in the commit message from "Exacting" to "Extracting".

2021-12-14 21:44 UTC, roydahan commented on main.py
> +            "There no exits '%d' different major tags in repo '%s'" % (latest_tags_size, repo_directory))
```suggestion
            f"The last {latest_tags_size} tags in {repo_directory} couldn't be extracted")
```

2021-12-14 23:06 UTC, Orenef11 commented on main.py
> +            "There no exits '%d' different major tags in repo '%s'" % (latest_tags_size, repo_directory))
Done

2021-12-15 09:46 UTC, roydahan approved these changes

2021-12-15 09:46 UTC, merged